spring:
  application:
    name: storemg
stripe:
  apiUrl: https://api.stripe.com
  enable: true
  timeout: 1000
  supported-currencies: USD,EUR,GBP
payment-gateway: paypal
mail:
  host: https://smtp.gmail.com
  port: 5761